### ISSUE TITLE
Module parse failed: Unexpected character '@' (1:0)

### ISSUE THREAD

**Issue by sadwik** [richard1015/cesium-navigation-es6#1]
./node_modules/cesium-navigation-es6/styles/cesium-navigation.less 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @import "Core";
| @import "Floating";
|

**Comment by richard1015** [comment]
pleass refer to this demo code :) 
[https://github.com/richard1015/cesium-vue-example/blob/master/src/components/CesiumViewer.vue](url)

**Comment by sadwik** [comment]
I converted the less file to css and it worked

**Comment by richard1015** [comment]
> I converted the less file to css and it worked

Other Cesium Plugin [https://github.com/richard1015/cesium-print](https://github.com/richard1015/cesium-print)
I hope you like it.
：）
