### ISSUE TITLE
好像不支持babel7

### ISSUE THREAD

**Issue by DickyNet** [richard1015/cesium-navigation-es6#12]
老大，webpack4+babel7 下打包出错 ，有办法解决么？
```

 ERROR  Failed to compile with 11 errors                                                                                                                                                              11:04:15

This dependency was not found:

* cesium/Source/Cesium.js in ./node_modules/cesium-navigation-es6/viewerCesiumNavigationMixin.js, ./node_modules/cesium-navigation-es6/CesiumNavigation.js and 9 others

To install it, you can run: npm install --save cesium/Source/Cesium.js

```

package.json内容如下：

```
{
  "name": "cesium_vue",
  "version": "1.0.0",
  "description": "A Vue.js project",
  "author": "Dicky",
  "private": true,
  "scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "start": "npm run dev",
    "unit": "jest --config test/unit/jest.conf.js --coverage",
    "e2e": "node test/e2e/runner.js",
    "test": "npm run unit && npm run e2e",
    "lint": "eslint --ext .js,.vue src test/unit test/e2e/specs",
    "build": "node build/build.js"
  },
  "dependencies": {
    "axios": "^0.19.2",
    "cesium": "^1.69.0",
    "cesium-navigation-es6": "^1.1.5",
    "cesium-print": "^1.0.6",
    "element-ui": "^2.13.1",
    "font-awesome": "^4.7.0",
    "sass-loader": "^8.0.2",
    "vue": "^2.5.2",
    "vue-router": "^3.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-decorators": "^7.0.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.0.0",
    "@babel/plugin-proposal-function-sent": "^7.0.0",
    "@babel/plugin-proposal-json-strings": "^7.0.0",
    "@babel/plugin-proposal-numeric-separator": "^7.0.0",
    "@babel/plugin-proposal-throw-expressions": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-syntax-import-meta": "^7.0.0",
    "@babel/plugin-syntax-jsx": "^7.0.0",
    "@babel/plugin-transform-modules-commonjs": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/register": "^7.0.0",
    "@babel/runtime-corejs2": "^7.9.6",
    "autoprefixer": "^7.1.2",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^9.0.0",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-jest": "^23.4.2",
    "babel-loader": "^8.1.0",
    "babel-plugin-dynamic-import-node": "^1.2.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "chalk": "^2.0.1",
    "chromedriver": "^2.27.2",
    "copy-webpack-plugin": "^4.0.1",
    "cross-spawn": "^5.0.1",
    "css-loader": "^3.5.3",
    "eslint": "^4.15.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.2.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^6.2.2",
    "file-loader": "^6.0.0",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "html-webpack-plugin": "^4.3.0",
    "jest": "^22.0.4",
    "jest-serializer-vue": "^0.3.0",
    "js-cookie": "^2.2.1",
    "mini-css-extract-plugin": "^0.9.0",
    "nightwatch": "^0.9.12",
    "node-notifier": "^5.1.2",
    "optimize-css-assets-webpack-plugin": "^5.0.3",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.6.0",
    "selenium-server": "^3.0.1",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^4.1.0",
    "vue-jest": "^1.0.2",
    "vue-loader": "^15.9.1",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^4.43.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

```

**Comment by richard1015** [comment]
确认一下配置文件

https://github.com/richard1015/cesium-vue-example/blob/master/build/webpack.dev.conf.js

**Comment by DickyNet** [comment]
> 确认一下配置文件
> 
> https://github.com/richard1015/cesium-vue-example/blob/master/build/webpack.dev.conf.js

换成你的配置文件也不行。npm run dev 还是同样的错误，我不加载指北针插件是没问题的。我的这个webpack.dev.conf.js与你的区别就是我是从cesium/Source里拷贝文件到三级文件夹下：

const cesiumSource = 'node_modules/cesium/Source'
    new CopyWebpackPlugin([{
      from: path.join(cesiumSource, 'Assets'),
      to: 'static/Cesium/Assets'
    }]),

**Comment by richard1015** [comment]
建议你直接克隆我那个项目  详细排查一下 : )

如果还未解决，请提供一个可复现的仓库给我

**Comment by DickyNet** [comment]
你的那个仓库不是最新版的webpack和babel7啊
你把我上面的package.json 替换下npm install 就知道了

**Comment by richard1015** [comment]
好的，稍后我看一下

**Comment by DickyNet** [comment]
> 好的，稍后我看一下

咋样，试了吗

**Comment by richard1015** [comment]
> > 好的，稍后我看一下
> 
> 咋样，试了吗

vue cli 4 已测试没问题 
https://github.com/richard1015/cesium-vue-example/tree/vuecli4

vue cli2 babel 7 正在测试

**Comment by richard1015** [comment]
> > 确认一下配置文件
> > https://github.com/richard1015/cesium-vue-example/blob/master/build/webpack.dev.conf.js
> 
> 换成你的配置文件也不行。npm run dev 还是同样的错误，我不加载指北针插件是没问题的。我的这个webpack.dev.conf.js与你的区别就是我是从cesium/Source里拷贝文件到三级文件夹下：
> 
> const cesiumSource = 'node_modules/cesium/Source'
> new CopyWebpackPlugin([{
> from: path.join(cesiumSource, 'Assets'),
> to: 'static/Cesium/Assets'
> }]),

你的配置文件明显有问题啊  1.69 的目录已经变了，跟babel 没关系

```
 // Copy Cesium Assets, Widgets, and Workers to a static directory
    new CopyWebpackPlugin([{ from: 'node_modules/cesium/Build/Cesium/Workers', to: 'Workers' }]),
    new CopyWebpackPlugin([{ from: 'node_modules/cesium/Build/Cesium/ThirdParty', to: 'ThirdParty' }]),
    new CopyWebpackPlugin([{ from: 'node_modules/cesium/Build/Cesium/Assets', to: 'Assets' }]),
    new CopyWebpackPlugin([{ from: 'node_modules/cesium/Build/Cesium/Widgets', to: 'Widgets' }]),
```

注意这个路径 node_modules/cesium/Build/Cesium/Assets

**Comment by DickyNet** [comment]
> > > 确认一下配置文件
> > > https://github.com/richard1015/cesium-vue-example/blob/master/build/webpack.dev.conf.js
> > 
> > 
> > 换成你的配置文件也不行。npm run dev 还是同样的错误，我不加载指北针插件是没问题的。我的这个webpack.dev.conf.js与你的区别就是我是从cesium/Source里拷贝文件到三级文件夹下：
> > const cesiumSource = 'node_modules/cesium/Source'
> > new CopyWebpackPlugin([{
> > from: path.join(cesiumSource, 'Assets'),
> > to: 'static/Cesium/Assets'
> > }]),
> 
> 你的配置文件明显有问题啊 1.69 的目录已经变了，跟babel 没关系
> 
> ```
>  // Copy Cesium Assets, Widgets, and Workers to a static directory
>     new CopyWebpackPlugin([{ from: 'node_modules/cesium/Build/Cesium/Workers', to: 'Workers' }]),
>     new CopyWebpackPlugin([{ from: 'node_modules/cesium/Build/Cesium/ThirdParty', to: 'ThirdParty' }]),
>     new CopyWebpackPlugin([{ from: 'node_modules/cesium/Build/Cesium/Assets', to: 'Assets' }]),
>     new CopyWebpackPlugin([{ from: 'node_modules/cesium/Build/Cesium/Widgets', to: 'Widgets' }]),
> ```
> 
> 注意这个路径 node_modules/cesium/Build/Cesium/Assets

我用你的那个webpack.dev.conf都不行，报的错误一样。另外我自己的那个配置 打包没问题的，地图能加载出来，图片资源引用都正常。

另外请教个问题，调用viewer.entities.add 添加一个文字和图标标注到地球上，为什么不是直接显示，要地图上随便拖动一下才显示 然后随着拖拽地图有时标注图标还会部分被地图挡住。前2天好的，后来改了一些页面上其它功能，就不正常了

```
        me.viewer.entities.add({
          id: label.name,
          name: label.name,
          position: {x: parseFloat(label.x), y: parseFloat(label.y), z: parseFloat(label.z)},
          description: label.desc,
          billboard: {
            image: pinBuilder.fromText(label.name, Cesium.Color.BLACK, 68).toDataURL(),
            distanceDisplayCondition: 2000,
            verticalOrigin: Cesium.VerticalOrigin.BOTTOM
          }
        })
```

**Comment by richard1015** [comment]
1. 关于cesium-navigation-es6 问题，建议你提交一个最小可复现仓库，我这边帮你排查一下问题
2. entities.add问题 
```
   /**
     * 绘制Cesium标注点
     */
    drawCesiumPoint(lat, lng, options) {
      viewer.entities.add({
        position: Cesium.Cartesian3.fromDegrees(lng, lat),
        name: options.name,
        //点样式
        point: {
          color: options.color || Cesium.Color.YELLOW,
          pixelSize: 9,
          outlineColor: Cesium.Color.WHITE,
          outlineWidth: 1
        }
      });
    },
```

**Comment by DickyNet** [comment]
> 1. 关于cesium-navigation-es6 问题，建议你提交一个最小可复现仓库，我这边帮你排查一下问题
> 2. entities.add问题
> 
> ```
>    /**
>      * 绘制Cesium标注点
>      */
>     drawCesiumPoint(lat, lng, options) {
>       viewer.entities.add({
>         position: Cesium.Cartesian3.fromDegrees(lng, lat),
>         name: options.name,
>         //点样式
>         point: {
>           color: options.color || Cesium.Color.YELLOW,
>           pixelSize: 9,
>           outlineColor: Cesium.Color.WHITE,
>           outlineWidth: 1
>         }
>       });
>     },
> ```

https://github.com/DickyNet/cesium-vue-test 我把代码传到仓库里了。

**Comment by DickyNet** [comment]
64行 import CesiumNavigation from 'cesium-navigation-es6'
149行 me.initNavigation()
177行 CesiumNavigation(me.viewer, options)

上面3行注释掉可以运行 ，保留就报昨天的错。后来我把你插件源码里所有引用cesium的地方改成下面这样就行了，不知道什么鬼（我vue模板里调用cesium 也是import * as Cesium from 'cesium/Cesium' 这样引用的）
`import { defined, DeveloperError } from 'cesium/Cesium.js'`

**Comment by DickyNet** [comment]
//set cesium alias name
      'cesium': path.resolve(__dirname, cesiumSource) 我好像知道了，webpack.base.conf里我加过别名，不好意思，浪费你的宝贵时间了哈
