### ISSUE TITLE
cesium 调用 cesium-navigation-es6 使用 TypeScript 语言 出错

### ISSUE THREAD

**Issue by z3214965** [richard1015/cesium-navigation-es6#13]
你好，使用cesium 调用 cesium-navigation-es6 使用 TypeScript 语言 出错。
![error](https://user-images.githubusercontent.com/18589356/81396088-51df6a80-9157-11ea-97dd-9bcf593246e8.PNG)
测试地址：https://github.com/z3214965/test-dem
麻烦你帮忙看下，谢谢。

**Comment by richard1015** [comment]
可以采用vue cli ,可以参考这个demo先试试  https://github.com/richard1015/cesium-vue-example

**Comment by z3214965** [comment]
我这是写封装，给别人调用。。。没有用到框架。

**Comment by richard1015** [comment]
请先确保你的项目可以正常运行， 我未使用cesium-navigation-es6插件  都报错

**Comment by z3214965** [comment]
不好意思，代码精简多了，已修改。

**Comment by z3214965** [comment]
不好意思，我找到问题所在，已解决。
