### ISSUE TITLE
升级到最新版本时,运行服务出现找不到对应依赖:cesium/Source/Cesium.js

### ISSUE THREAD

**Issue by HAPPYFUNSIGHT** [richard1015/cesium-navigation-es6#14]
Cesium版本为：1.50
```
"cesium": "^1.50.0", "cesium-navigation-es6": "^1.1.6",
```
 ERROR  Failed to compile with 11 errors                                                                                                         11:04:53 AM
This dependency was not found:

* cesium/Source/Cesium.js in ./node_modules/cesium-navigation-es6/viewerCesiumNavigationMixin.js, ./node_modules/cesium-navigation-es6/CesiumNavigation.js and 9 others

To install it, you can run: npm install --save cesium/Source/Cesium.js

 ERROR CODE  ERR_WEBPACK_MODULE_NOT_FOUND

**Comment by richard1015** [comment]
感谢您的反馈，可以先参考一下 
https://github.com/richard1015/cesium-vue-example

如果还未解决，请提供一个最小可复现仓库
