### ISSUE TITLE
Need to update tooltip text

### ISSUE THREAD

**Issue by nik10-mah** [richard1015/cesium-navigation-es6#18]
Need to set the **name** property via props as per screenshot
![image](https://user-images.githubusercontent.com/4695534/85414832-3ce55c00-b58a-11ea-9e41-75fe68048d19.png)

**Comment by richard1015** [comment]
Thank you very much for your feedback. I will optimize this problem in the near future

**Comment by ONEGISER** [comment]
> Need to set the **name** property via props as per screenshot ![image](https://user-images.githubusercontent.com/4695534/85414832-3ce55c00-b58a-11ea-9e41-75fe68048d19.png)
最近太忙  没顾上   2.0.3已经支持
