### ISSUE TITLE
style problem

### ISSUE THREAD

**Issue by hellorayza** [richard1015/cesium-navigation-es6#2]
##### Environment  

react、cesium1.60

##### Situation

After add  `import CesiumNavigation from "cesium-navigation-es6";   `     
then add

```javascript    
var options = {};
// 用于在使用重置导航重置地图视图时设置默认视图控制。接受的值是Cesium.Cartographic 和 Cesium.Rectangle.
options.defaultResetView = Cesium.Rectangle.fromDegrees(80, 22, 130, 50);
// 用于启用或禁用罗盘。true是启用罗盘，false是禁用罗盘。默认值为true。如果将选项设置为false，则罗盘将不会添加到地图中。
options.enableCompass= true;
// 用于启用或禁用缩放控件。true是启用，false是禁用。默认值为true。如果将选项设置为false，则缩放控件将不会添加到地图中。
options.enableZoomControls= false;
// 用于启用或禁用距离图例。true是启用，false是禁用。默认值为true。如果将选项设置为false，距离图例将不会添加到地图中。
options.enableDistanceLegend= false;
// 用于启用或禁用指南针外环。true是启用，false是禁用。默认值为true。如果将选项设置为false，则该环将可见但无效。
options.enableCompassOuterRing= true;
CesiumNavigation(viewer, options);
```    
Howerver I can't move and  zoom .

![resultPic][]    
my react can‘t eject so does't support less. Is that the reason?

[resultPic]:https://s2.ax1x.com/2019/08/09/ebJkLQ.png

**Comment by richard1015** [comment]
Please provide minimum replication Git

**Comment by hellorayza** [comment]
hello,I created a warehouse.thanks 
https://github.com/hellorayza/react-cesium-app

**Comment by richard1015** [comment]
Has been repaired and push to your project Pull Request
Thank you for finding out the problem.
