### ISSUE TITLE
npm中cesium版本升级

### ISSUE THREAD

**Issue by wuzhenzhen1314** [richard1015/cesium-navigation-es6#20]
你好，现在cesium版本是1.71.0，npm中cesium-navigation-es6包最新1.1.6，它package中使用的cesium是1.6.4，如果项目使用cesium版本是1.71.0，就无法使用cesium-navigation-es6包（除非手动改这个包的代码），npm中可以更新一下吗？使得cesium版本一致，非常感谢！

**Comment by richard1015** [comment]
可以的，马上跟进

**Comment by richard1015** [comment]
已升级
