### ISSUE TITLE
After the plug-in was introduced--ERROR in ./node_modules/cesium/Source/Core/Resource.js

### ISSUE THREAD

**Issue by LaogaKAKA** [richard1015/cesium-navigation-es6#21]
The error statement:   
var http = URL.protocol === "https:" ? require("https") : require("http");
var zlib = require("zlib");

ERROR in ./node_modules/zlib/lib/zlib.js
Module not found: Error: Can't resolve './zlib_bindings' in 'D:\Project\Cesium\scAPPFronted-Navigation\node_modules\zlib\lib'
ERROR in ./node_modules/cesium/Source/Core/Resource.js
Module not found: Error: Can't resolve 'http' in 'D:\Project\Cesium\scAPPFronted-Navigation\node_modules\cesium\Source\Core'
ERROR in ./node_modules/cesium/Source/Core/Resource.js
Module not found: Error: Can't resolve 'https' in 'D:\Project\Cesium\scAPPFronted-Navigation\node_modules\cesium\Source\Core'

Otherwise, my cesium project is build in angular

**Comment by richard1015** [comment]
Is it possible to provide a minimum replication repository git

**Comment by LaogaKAKA** [comment]
I'm sorry, I can't provide it because it involves the confidentiality regulations. My preliminary judgment is that questions about colleagues' modules, thanks a lot :)
&nbsp;

贾军辉
GIS应用研发部
自然资源部第三航测遥感院
JohnWin Jia
GIS application R &amp; D department
The Third Institute of Photogrammetry and Remote Sensing, Ministry of Natural Resources

Email:gagahelloworld@gmail.com


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "richard1015"<notifications@github.com&gt;; 
发送时间: 2020年9月15日(星期二) 上午9:33
收件人: "richard1015/cesium-navigation-es6"<cesium-navigation-es6@noreply.github.com&gt;; 
抄送: "活着的梦想"<1031011186@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [richard1015/cesium-navigation-es6] After the plug-in was introduced--ERROR in ./node_modules/cesium/Source/Core/Resource.js (#21)





 
Is it possible to provide a minimum replication repository git

**Comment by richard1015** [comment]
@LaogaKAKA    好的，有问题随时沟通

**Comment by LaogaKAKA** [comment]
&nbsp;

贾军辉
GIS应用研发部
自然资源部第三航测遥感院
JohnWin Jia
GIS application R &amp; D department
The Third Institute of Photogrammetry and Remote Sensing, Ministry of Natural Resources

Email:gagahelloworld@gmail.com


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "richard1015"<notifications@github.com&gt;; 
发送时间: 2020年9月15日(星期二) 上午9:47
收件人: "richard1015/cesium-navigation-es6"<cesium-navigation-es6@noreply.github.com&gt;; 
抄送: "活着的梦想"<1031011186@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [richard1015/cesium-navigation-es6] After the plug-in was introduced--ERROR in ./node_modules/cesium/Source/Core/Resource.js (#21)





 
@LaogaKAKA    好的，有问题随时沟通

**Comment by iStImetOgAme** [comment]
这个问题您解决了吗，我也遇到了同样的问题
