### ISSUE TITLE
在html页面直接viewerCesiumNavigationMixin.min.js文件，报Uncaught TypeError: defineProperties is not a function。

### ISSUE THREAD

**Issue by xiaolingis** [richard1015/cesium-navigation-es6#24]
cesium1.50版本没有问题，换成cesium1.73，在html页面这样引入<script src="viewerCesiumNavigationMixin.min.js"></script>，是不是不能采用这种方式引入？

**Comment by ONEGISER** [comment]
这个需要你将源码的defineProperties 改成Object.defineProperties

**Comment by richard1015** [comment]
升级 2.0.1

https://www.npmjs.com/package/cesium-navigation-es6/v/2.0.1
