### ISSUE TITLE
使用defaultResetView，自定义中国范围却显示到0，0坐标

### ISSUE THREAD

**Issue by liuchang567** [richard1015/cesium-navigation-es6#25]
代码两个都是定位到0，0，不能定位到下面坐标点的范围
options.defaultResetView = new Cesium.Cartographic.fromDegrees(117.704, 38.34, 9000)
// options.defaultResetView = Cesium.Rectangle.fromDegrees(80, 22, 130, 50)
但是我直接使用
this.camera.flyTo({
        destination: this.scene.globe.ellipsoid.cartographicToCartesian(new Cesium.Cartographic.fromDegrees(117.704, 38.34, 9000)),
      })
视图时可以跳到指定位置

**Comment by richard1015** [comment]
可以参考一下demo

Demo
[cesium plugin /demo](https://richard1015.github.io/cesium/)
Code Demo
https://github.com/richard1015/cesium-vue-example

**Comment by liuchang567** [comment]
弄出来了，忘记关闭了
options.defaultResetView =  Cesium.Cartographic 写法不行
改成
options = {
  defaultResetView: Cesium.Cartographic
}
就可以解决了
有试过断点到源码里面，是没有传到参数进来，源码还没有研究完，所以不知道为啥2种写法，一个可以一个不可以，我项目也是基于vue开发的
