### ISSUE TITLE
依赖包引用问题

### ISSUE THREAD

**Issue by anqimen** [richard1015/cesium-navigation-es6#29]
* cesium/Source/Cesium.js in ./node_modules/cesium-navigation-es6/viewerCesiumNavigationMixin.js, ./node_modules/cesium-navigation-es6/core/registerKnockoutBindings.js and 1 other

该段提示即安装依赖后出现的问题,原因是无法在当前依赖包文件中找到对应的文件【cesium/Source/Cesium.js】
按理来说即使无法在本依赖文件中找不到也会往上一级一级的查找，此问题让本人百思不得其解，往看到此问题后能及时回复

**Comment by richard1015** [comment]
尝试升级 2.0.1版本
