### ISSUE TITLE
一个错误

### ISSUE THREAD

**Issue by z3214965** [richard1015/cesium-navigation-es6#3]
你好：
当前在项目中引用cesium-navigation-es6时，发生以下错误：
![捕获](https://user-images.githubusercontent.com/18589356/71577462-345a1e80-2b2f-11ea-8bfd-330f6ea8f374.PNG)
我不知道怎么解决，麻烦您，帮忙看下，谢谢！

**Comment by richard1015** [comment]
是否可以提供一下最小可复现仓库，或者你查看一下demo
https://github.com/richard1015/cesium-vue-example

**Comment by z3214965** [comment]
[https://github.com/z3214965/test-cesium-navigation-es6](url)
这是地址，当我运行，npm start时发生错误，麻烦你了，谢谢！

**Comment by richard1015** [comment]
@z3214965 
demo  
[https://github.com/richard1015/cesium-webpack-example](https://github.com/richard1015/cesium-webpack-example)
[https://github.com/richard1015/cesium-vue-example](https://github.com/richard1015/cesium-vue-example)

happy new year

**Comment by richard1015** [comment]
@z3214965    怎么样了，是否已解决

**Comment by z3214965** [comment]
@richard1015 刚测试网，已解决，非常感谢，happy new year！
