### ISSUE TITLE
最低的cesium依赖是1.88？

### ISSUE THREAD

**Issue by fuuhoo** [richard1015/cesium-navigation-es6#33]
低版本的cesium没办法用吗

**Comment by ONEGISER** [comment]
> 

你的版本是多少呢？

**Comment by fuuhoo** [comment]
> > 
> 
> 你的版本是多少呢？

我的是1.68。看到前面最低支持1.69了，然后我升级到1.69了，目前报Failed to resolve loader: less-loader的错。但是我已经装了

**Comment by fuuhoo** [comment]
> > 
> 
> 你的版本是多少呢？

好了，是我的版本问题。我这边高版本的less提示getoptions错误，低版本下的less文件有错误，改了一下就好了

**Comment by ONEGISER** [comment]
你也可以直接用umd的方式

**Comment by ONEGISER** [comment]
> 你也可以直接用umd的方式
你也可以直接用umd的方式

**Comment by ONEGISER** [comment]
> > > 
> > 
> > 
> > 你的版本是多少呢？
> 
> 好了，是我的版本问题。我这边高版本的less提示getoptions错误，低版本下的less文件有错误，改了一下就好了

你也可以直接用umd的方式

**Comment by fuuhoo** [comment]
> > > > 
> > > 
> > > 
> > > 你的版本是多少呢？
> > 
> > 
> > 好了，是我的版本问题。我这边高版本的less提示getoptions错误，低版本下的less文件有错误，改了一下就好了
> 
> 你也可以直接用umd的方式

感谢大佬！！！
