### ISSUE TITLE
Module doesn't work on Cesium 1.63

### ISSUE THREAD

**Issue by gogo1211** [richard1015/cesium-navigation-es6#4]
![image](https://user-images.githubusercontent.com/44463883/71596818-c7cf2780-2b0e-11ea-884f-4cef8296f9fd.png)

**Comment by richard1015** [comment]
@gogo1211    Please upgrade cesium-navigation-es6 Latest version

**Comment by richard1015** [comment]
demo  [https://github.com/richard1015/cesium-vue-example](https://github.com/richard1015/cesium-vue-example)

happy new year

**Comment by gogo1211** [comment]
@richard1015 
Happy new year!
Thank you for the quick work!
