### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by yolo-ling** [richard1015/cesium-navigation-es6#6]
请教一下,指北针的  N的样式,可以修改吗?options没有找到文档

**Comment by richard1015** [comment]
暂时不支持，有兴趣，可以自己深入研究一下

**Comment by DickyNet** [comment]
`Cesium-navigation/ResetViewNavigationControl:   options.defaultResetView Cesium rectangle is  invalid! `

点击重置视图按钮报这个错误怎么回事呢？配置如下：
```
    // 初始化指北针
    initNavigation () {
      var options = {}
      // 用于在使用重置导航重置地图视图时设置默认视图控制。接受的值是Cesium.Cartographic 和 Rectangle.
      options.defaultResetView = Rectangle.fromDegrees(80, 22, 130, 50)
      // 用于启用或禁用罗盘。true是启用罗盘，false是禁用罗盘。默认值为true。如果将选项设置为false，则罗盘将不会添加到地图中。
      options.enableCompass = true
      // 用于启用或禁用缩放控件。true是启用，false是禁用。默认值为true。如果将选项设置为false，则缩放控件将不会添加到地图中。
      options.enableZoomControls = true
      // 用于启用或禁用距离图例。true是启用，false是禁用。默认值为true。如果将选项设置为false，距离图例将不会添加到地图中。
      options.enableDistanceLegend = true
      // 用于启用或禁用指南针外环。true是启用，false是禁用。默认值为true。如果将选项设置为false，则该环将可见但无效。
      options.enableCompassOuterRing = true
      CesiumNavigation(viewer, options)
    }
```

**Comment by richard1015** [comment]
> `Cesium-navigation/ResetViewNavigationControl: options.defaultResetView Cesium rectangle is invalid! `
> 
> 点击重置视图按钮报这个错误怎么回事呢？配置如下：
> 
> ```
>     // 初始化指北针
>     initNavigation () {
>       var options = {}
>       // 用于在使用重置导航重置地图视图时设置默认视图控制。接受的值是Cesium.Cartographic 和 Rectangle.
>       options.defaultResetView = Rectangle.fromDegrees(80, 22, 130, 50)
>       // 用于启用或禁用罗盘。true是启用罗盘，false是禁用罗盘。默认值为true。如果将选项设置为false，则罗盘将不会添加到地图中。
>       options.enableCompass = true
>       // 用于启用或禁用缩放控件。true是启用，false是禁用。默认值为true。如果将选项设置为false，则缩放控件将不会添加到地图中。
>       options.enableZoomControls = true
>       // 用于启用或禁用距离图例。true是启用，false是禁用。默认值为true。如果将选项设置为false，距离图例将不会添加到地图中。
>       options.enableDistanceLegend = true
>       // 用于启用或禁用指南针外环。true是启用，false是禁用。默认值为true。如果将选项设置为false，则该环将可见但无效。
>       options.enableCompassOuterRing = true
>       CesiumNavigation(viewer, options)
>     }
> ```

1.1.6已修复，感谢感谢反馈
