### ISSUE TITLE
1.67版本不能用了

### ISSUE THREAD

**Issue by gitzhang** [richard1015/cesium-navigation-es6#8]
1.67版本不能用了，请求升级

**Comment by richard1015** [comment]
无法使用吗？

**Comment by gitzhang** [comment]
![image](https://user-images.githubusercontent.com/2832192/77142012-c7b14900-6ab9-11ea-9be1-1a2689959103.png)
加载后报错

**Comment by gitzhang** [comment]
看了下原因，Cesium包里没有defineProperties方法了。 自己定义了一个
`var defineProperties = Object.defineProperties` 解决了

**Comment by richard1015** [comment]
好的
