### ISSUE TITLE
Cesium1.67.0中已经删除了defineProperties方法

### ISSUE THREAD

**Issue by MOLVMIN** [richard1015/cesium-navigation-es6#9]
Cesium1.67.0中已经删除了defineProperties方法，改用原生Object.defineProperties替代，但cesium-navigation-es6插件最新版本代码中还没有更改过来，使用时会报错。

**Comment by richard1015** [comment]
好的，感谢您的反馈，我这边跟进修复一下

**Comment by wxyer** [comment]
希望能及时更新下包，在此拜谢了

**Comment by bestsamcn** [comment]
同样的问题，希望早点更新解决啊

**Comment by richard1015** [comment]
正在处理中,马上修复

**Comment by richard1015** [comment]
最新版已修复  请参考 
https://github.com/richard1015/cesium-vue-example/


感谢大家的反馈 :)
